# Generated by Django 4.1.7 on 2023-02-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('EmployeID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='EmpID')),
                ('Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('JoiningDate', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.CharField(max_length=50)),
                ('DefaultSalary', models.IntegerField(default=25000)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.CharField(max_length=50)),
                ('DefaultSalary', models.IntegerField(default=20000)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='BussinesAnalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tool', models.CharField(max_length=50)),
                ('DefaultSalary', models.IntegerField(default=15000)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.employe')),
            ],
        ),
    ]
